apiVersion: v1
kind: Service
metadata:
  name: healing-simulator
  labels:
    app.kubernetes.io/name: healing-simulator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: healing-simulator
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
